/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CanvasBG: typeof import('./src/components/canvasBG/index.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Typed: typeof import('./src/components/typed/index.vue')['default']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarForm: typeof import('@varlet/ui')['_FormComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarInput: typeof import('@varlet/ui')['_InputComponent']
    VarSpace: typeof import('@varlet/ui')['_SpaceComponent']
    VarStyleProvider: typeof import('@varlet/ui')['_StyleProviderComponent']
  }
}
